// Generated by Supabase (MCP generate_typescript_types) for project spvysjjtmyknagjnguqq.
// Do not edit by hand — regenerate after schema changes. Used only inside src/services/supabase
// and tests; UI code works with the domain types in src/types/domain.ts.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      admin_profiles: {
        Row: {
          created_at: string
          display_name: string
          user_id: string
        }
        Insert: {
          created_at?: string
          display_name?: string
          user_id: string
        }
        Update: {
          created_at?: string
          display_name?: string
          user_id?: string
        }
        Relationships: []
      }
      competition_settings: {
        Row: {
          competition_date: string
          id: number
          max_age: number
          maximum_teams: number
          min_age: number
          next_registration_seq: number
          registration_open: boolean
          updated_at: string
        }
        Insert: {
          competition_date: string
          id?: number
          max_age?: number
          maximum_teams?: number
          min_age?: number
          next_registration_seq?: number
          registration_open?: boolean
          updated_at?: string
        }
        Update: {
          competition_date?: string
          id?: number
          max_age?: number
          maximum_teams?: number
          min_age?: number
          next_registration_seq?: number
          registration_open?: boolean
          updated_at?: string
        }
        Relationships: []
      }
      team_members: {
        Row: {
          aadhaar_file_name: string
          aadhaar_mime_type: string
          aadhaar_size_bytes: number
          aadhaar_storage_path: string
          course_details: string | null
          created_at: string
          date_of_birth: string
          district: string
          employer: string | null
          full_name: string
          id: string
          institution: string | null
          is_aalim: boolean
          member_number: number
          mobile_number: string
          occupation: string | null
          participant_status: Database["public"]["Enums"]["participant_status"]
          residential_address: string
          studying_in_madrasa: boolean
          team_id: string
          updated_at: string
        }
        Insert: {
          aadhaar_file_name: string
          aadhaar_mime_type: string
          aadhaar_size_bytes: number
          aadhaar_storage_path: string
          course_details?: string | null
          created_at?: string
          date_of_birth: string
          district: string
          employer?: string | null
          full_name: string
          id?: string
          institution?: string | null
          is_aalim: boolean
          member_number: number
          mobile_number: string
          occupation?: string | null
          participant_status: Database["public"]["Enums"]["participant_status"]
          residential_address: string
          studying_in_madrasa: boolean
          team_id: string
          updated_at?: string
        }
        Update: {
          aadhaar_file_name?: string
          aadhaar_mime_type?: string
          aadhaar_size_bytes?: number
          aadhaar_storage_path?: string
          course_details?: string | null
          created_at?: string
          date_of_birth?: string
          district?: string
          employer?: string | null
          full_name?: string
          id?: string
          institution?: string | null
          is_aalim?: boolean
          member_number?: number
          mobile_number?: string
          occupation?: string | null
          participant_status?: Database["public"]["Enums"]["participant_status"]
          residential_address?: string
          studying_in_madrasa?: boolean
          team_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "team_members_team_id_fkey"
            columns: ["team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
        ]
      }
      teams: {
        Row: {
          admin_note: string | null
          consented_at: string
          created_at: string
          id: string
          registration_number: string
          status: Database["public"]["Enums"]["registration_status"]
          submission_id: string
          updated_at: string
        }
        Insert: {
          admin_note?: string | null
          consented_at: string
          created_at?: string
          id?: string
          registration_number: string
          status?: Database["public"]["Enums"]["registration_status"]
          submission_id: string
          updated_at?: string
        }
        Update: {
          admin_note?: string | null
          consented_at?: string
          created_at?: string
          id?: string
          registration_number?: string
          status?: Database["public"]["Enums"]["registration_status"]
          submission_id?: string
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      admin_dashboard_stats: { Args: never; Returns: Json }
      admin_delete_team: { Args: { p_team_id: string }; Returns: Json }
      admin_list_orphan_uploads: {
        Args: { p_older_than?: string }
        Returns: Json
      }
      admin_set_team_status: {
        Args: {
          p_note?: string
          p_status: Database["public"]["Enums"]["registration_status"]
          p_team_id: string
        }
        Returns: Json
      }
      get_registration_availability: { Args: never; Returns: Json }
      register_team: {
        Args: { p_consent: Json; p_members: Json; p_submission_id: string }
        Returns: Json
      }
    }
    Enums: {
      participant_status: "student" | "working"
      registration_status: "submitted" | "verified" | "rejected" | "cancelled"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      participant_status: ["student", "working"],
      registration_status: ["submitted", "verified", "rejected", "cancelled"],
    },
  },
} as const
